
services:
  service:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://cookie_authy_user:cookie_authy_pass@db:5432/cookie_authy_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: cookie_authy_user
      POSTGRES_PASSWORD: cookie_authy_pass
      POSTGRES_DB: cookie_authy_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cookie_authy_user -d cookie_authy_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
