# Generated by Django 5.2.4 on 2025-07-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('Architecture & Patterns', 'Architecture & Patterns'), ('Language & Core Tools', 'Language & Core Tools'), ('Security', 'Security'), ('Testing', 'Testing'), ('Jetpack Compose & UI', 'Jetpack Compose & UI'), ('Data & Storage', 'Data & Storage'), ('Networking', 'Networking'), ('Dependency Injection', 'Dependency Injection'), ('Navigation & Lifecycle', 'Navigation & Lifecycle'), ('Firebase & Cloud', 'Firebase & Cloud'), ('App Distribution & Analytics', 'App Distribution & Analytics'), ('Performance & Optimization', 'Performance & Optimization'), ('Other', 'Other')], default='Other', max_length=50)),
                ('definition', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Glossary Terms',
                'ordering': ['term'],
            },
        ),
    ]
